=== duartencanoso/TrabIndividual1IS/servidor/rest/schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "object",
  "properties": {
    "id": { "type": "integer" },
    "nome": { "type": "string" },
    "marca": { "type": "string" },
    "preco": { "type": "number" },
    "stock": { "type": "integer" },
    "caracteristicas": {
      "type": "object",
      "properties": {
        "tela": { "type": "string" },
        "bateria": { "type": "string" },
        "armazenamento": { "type": "string" }
      }
    }
  },
  "required": ["id", "nome", "marca", "preco", "stock", "caracteristicas"]
}

=== duartencanoso/TrabIndividual1IS/servidor/grpc/produtos.json
[
  {
    "id": 1,
    "nome": "Smartphone",
    "marca": "Apple",
    "preco": 299.99,
    "stock": 25,
    "caracteristicas": {
      "tela": "6.5 polegadas",
      "bateria": "4000mAh",
      "armazenamento": "128GB"
    }
  },
  {
    "id": 2,
    "nome": "Auriculares Bluetooth",
    "marca": "Samsung",
    "preco": 59.9,
    "stock": 50,
    "caracteristicas": {
      "tela": "n/a",
      "bateria": "500mAh",
      "armazenamento": "n/a"
    }
  },
  {
    "id": 3,
    "nome": "Coluna Bluetooth",
    "marca": "JBL",
    "preco": 79.99,
    "stock": 30,
    "caracteristicas": {
      "tela": "n/a",
      "bateria": "2000mAh",
      "armazenamento": "n/a"
    }
  }
]

=== duartencanoso/TrabIndividual1IS/cliente/importar/produtos_importar.json
[
  {
    "id": 8,
    "nome": "Fones sem fio",
    "marca": "Pionner",
    "preco": 299.99,
    "stock": 5,
    "caracteristicas": {
      "tela": "n/a",
      "bateria": "6000mAh",
      "armazenamento": "n/a"
    }
  },
  {
    "id": 9,
    "nome": "CÃ¢mara DSLR",
    "marca": "Canon",
    "preco": 600.99,
    "stock": 8,
    "caracteristicas": {
      "tela": "3 polegadas",
      "bateria": "1200mAh",
      "armazenamento": "SDcard"
    }
  }
]

=== duartencanoso/TrabIndividual1IS/servidor/dados/produtos.json
[
  {
    "id": 1,
    "nome": "Iphone 15 pro max",
    "marca": "Apple",
    "preco": 900.0,
    "stock": 30,
    "caracteristicas": {
      "tela": "6.1",
      "bateria": "500mAh",
      "armazenamento": "256"
    }
  },
  {
    "id": 2,
    "nome": "Auriculares Bluetooth",
    "marca": "Samsung",
    "preco": 59.9,
    "stock": 50,
    "caracteristicas": {
      "tela": "n/a",
      "bateria": "500mAh",
      "armazenamento": "n/a"
    }
  },
  {
    "id": 3,
    "nome": "Coluna Bluetooth",
    "marca": "JBL",
    "preco": 79.99,
    "stock": 30,
    "caracteristicas": {
      "tela": "n/a",
      "bateria": "2000mAh",
      "armazenamento": "n/a"
    }
  },
  {
    "id": 4,
    "nome": "Smartwatch GEN 8",
    "marca": "Garmin",
    "preco": 200.99,
    "stock": 20,
    "caracteristicas": {
      "tela": "1.4 polegadas",
      "bateria": "300mAh",
      "armazenamento": "4GB"
    }
  },
  {
    "id": 5,
    "nome": "Portatil UltraSlim",
    "marca": "Lenovo",
    "preco": 849.0,
    "stock": 10,
    "caracteristicas": {
      "tela": "15.6 polegadas",
      "bateria": "6000mAh",
      "armazenamento": "512GB SSD"
    }
  },
  {
    "id": 6,
    "nome": "Tablet Pro 11",
    "marca": "Huawei",
    "preco": 500.0,
    "stock": 18,
    "caracteristicas": {
      "tela": "11 polegadas",
      "bateria": "7500mAh",
      "armazenamento": "256GB"
    }
  },
  {
    "id": 7,
    "nome": "Telemovel Android",
    "marca": "Xiaomi",
    "preco": 500.0,
    "stock": 20,
    "caracteristicas": {
      "tela": "13 polegadas",
      "bateria": "1500mAh",
      "armazenamento": "256GB"
    }
  }
]
